### ISSUE TITLE
TS type errors

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [aurelia-ui-toolkits/aurelia-materialize-bridge#496]
Hi, I think, since it has been converted to TS, we have the following errors.

```
[at-loader] Checking finished with 2 errors
[at-loader] ./node_modules/aurelia-materialize-bridge/dist/commonjs/collapsible/collapsible.d.ts:14:104 
    TS2315: Type 'JQuery' is not generic. 

[at-loader] ./node_modules/aurelia-materialize-bridge/dist/commonjs/datepicker/datepicker.d.ts:20:14 
    TS2304: Cannot find name 'DatePickerOptions'. 
```

**Comment by MaximBalaganskiy** [comment]
Could be that jQuery and pickadate typings are not in dependencies, I'll
check after Easter. Although, all our internal projects compile fine...

**Comment by MaximBalaganskiy** [comment]
Fixed via https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/commit/5f698cef5077b58dd4274f94dc5bab3668b9a76d

**Comment by HIRANO-Satoshi** [comment]
I tested the new release 0.33.2. Thanks for it.

The DatePickerOptions issue has been gone. But we are still having the jQuery issue.

```
[at-loader] Checking finished with 1 errors
[at-loader] ./node_modules/aurelia-materialize-bridge/dist/commonjs/collapsible/collapsible.d.ts:14:104 
    TS2315: Type 'JQuery' is not generic. 
```

The following code in collapsible.ts 

```
	buildCollapsibleOpenCloseCallbackHandler(handler: (element: Element) => {}) {
		return typeof (handler) === "function" ?
			(targetElementJquery: JQuery) => {
				const targetElement = targetElementJquery[0];

				handler(targetElement);
			} : null;
	}
```
generates the following code in collapsible.d.ts.

```
    buildCollapsibleOpenCloseCallbackHandler(handler: (element: Element) => {}): (targetElementJquery: JQuery<HTMLElement>) => void;
```
I have no idea why JQuery is treated as generic and "JQuery" is not "jQuery".

**Comment by MaximBalaganskiy** [comment]
Could you please check if you have `node_modules/@types/jquery` folder?
I get the same error when I remove mine. That's why I added this dependency.

**Comment by HIRANO-Satoshi** [comment]
Yes. I have it for sure. I did "rm -rf node_modules; yarn install; yarn upgrade".

**Comment by HIRANO-Satoshi** [comment]
There is src/materialize.d.ts and JQuery is defined as an interface. It's not generic.

**Comment by MaximBalaganskiy** [comment]
That's fine. There should be `node_modules/@types/jquery`. Not sure is yarn downloads that... Please check if it's there.

**Comment by HIRANO-Satoshi** [comment]
I have node_modules/@types/jquery and its contents.

If you intended to use jQuery rather than JQuery and to use @types/jquery, we need

/// <reference path="../../node_modules/@types/jquery/index.d.ts" /> 

or something like that at somewhere in collapsible.ts, right?

**Comment by MaximBalaganskiy** [comment]
You need a specific 'node_modules/@types/jQuery' package. Please confirm
you have it installed. Also worth checking the demo app source - it's built
with webpack and typescript.

**Comment by HIRANO-Satoshi** [comment]
You are right. I had ^2.0 of `@types/jquery` in my package.json. 

Now I updated it to ^3.3.0 and the type error has been disappeared. 

Thanks so much!
